logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    com.kgisl.springBootDemo: ALL
  
  pattern:
    console: "- %msg%n"
    file: "*[%-5p]-- %m--%n"
  file: logs/springBootDemo.log
server:
  port: 9091
spring:
  datasource:
    url: jdbc:h2:file:~/springBootDemo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: update